{% set name = "docker-squash" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 74dd70412ddcf570bcd322567929062342793d1ec70c63b5371cc9e2808ae2ef

build:
  entry_points:
    - docker-squash=docker_squash.cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docker-py
    - six

test:
  imports:
    - docker_squash
  commands:
    - pip check
    - docker-squash --help
  requires:
    - pip

about:
  home: https://github.com/goldmann/docker-squash
  summary: Docker layer squashing tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
